### ISSUE TITLE
RTS shutter on Vera

### ISSUE THREAD

**Issue by MikeSpoon** [vosmont/Vera-Plugin-ZiBlueGateway#5]
I'm trying to add a Somfy RTSshutter to my VERAplus through the rfplayer. I followed your steps on the readme . with the remote control the shutter is discovered and added to managed devices et dashboard. But it still not works to open or close the shutter. did I missed something?

**Comment by vosmont** [comment]
Hello @MikeSpoon, what version of the plugin do you use ?

I've just merged the development branch with master. The 1.3.7 has been reported as working with RTS shutters.

**Comment by MikeSpoon** [comment]
I was still with a 1.2.x version. I updated to 1.3.7 and made a try today. But it was still the same. Shutter discovered and added to devices. but click on open or close making no action.
Something else I can try?

**Comment by vosmont** [comment]
When a RTS shutter appears in the "Discovered equipments" tab, it's the remote control of the shutter.

You have to add a new virtual equipment ("New equipment" tab) and teach it to your real shutter.
This virtual equipment is then like a remote control.
